-- =====================================================================
-- THE PET HOUSE - Kits promocionais na loja online
-- Rode este arquivo inteiro no Supabase > SQL Editor > New query > Run.
-- É idempotente: pode rodar mais de uma vez sem quebrar nada.
--
-- Um kit junta produtos diferentes num preço só: "Ração Quatree Gourmet
-- 10 kg + 10 sachês por R$ 179,90". O kit NÃO é um produto novo — ele
-- aponta para os produtos que já existem. Na hora do pedido, o servidor
-- abre o kit em uma linha por componente, então o estoque baixa de cada
-- um e a venda no PDV entra item a item, sem mexer em nada do fluxo.
-- =====================================================================

create table if not exists public.kits (
  id           bigint generated by default as identity primary key,
  nome         text          not null,
  descricao    text,
  preco        numeric(10,2) not null,
  foto_url     text,
  ativo        boolean       not null default true,
  visivel_loja boolean       not null default true,
  created_at   timestamptz   not null default now(),
  updated_at   timestamptz   not null default now()
);

create table if not exists public.kit_itens (
  id         bigint generated by default as identity primary key,
  kit_id     bigint not null references public.kits(id)     on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  tipo_venda text   not null default 'unidade',   -- saco | kg | unidade
  quantidade numeric(10,3) not null default 1
);

create index if not exists kit_itens_kit_idx on public.kit_itens (kit_id);

comment on table  public.kits            is 'combos da loja online; apontam para produtos existentes';
comment on column public.kits.preco      is 'preço fechado do kit';
comment on column public.kit_itens.tipo_venda is 'como o componente sai: saco | kg | unidade';

-- Mesma política das outras tabelas da loja (orders, order_items): a API
-- fala com o banco pela chave anon, então é ela que precisa passar.
alter table public.kits      enable row level security;
alter table public.kit_itens enable row level security;

drop policy if exists loja_kits_all      on public.kits;
drop policy if exists loja_kit_itens_all on public.kit_itens;
create policy loja_kits_all      on public.kits      for all to anon, authenticated using (true) with check (true);
create policy loja_kit_itens_all on public.kit_itens for all to anon, authenticated using (true) with check (true);
